version: "3"
services:
  db:
    image: "postgres"
    restart: always
    container_name: "data_postgres"
    environment:
      - POSTGRES_USER=Pasha
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432" 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # server:
  #   build:
  #     context: ..
  #     dockerfile: ./deployments/dockerfile-server
  #   restart: on-failure
  #   env_file:
  #     - ../configs/server.env  